"""add timing fields to execution_traces

Revision ID: bd4dae3e8321
Revises: cc83b3f059b0
Create Date: 2026-04-27 01:25:54.452294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4dae3e8321'
down_revision: Union[str, Sequence[str], None] = 'cc83b3f059b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_traces', sa.Column('execute_time', sa.DateTime(), nullable=True))
    op.add_column('execution_traces', sa.Column('queue_time_ms', sa.Float(), nullable=True))
    op.add_column('execution_traces', sa.Column('actual_exec_time_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_traces', 'actual_exec_time_ms')
    op.drop_column('execution_traces', 'queue_time_ms')
    op.drop_column('execution_traces', 'execute_time')
    # ### end Alembic commands ###
